DROP TABLE NOTES IF EXISTS;
CREATE TABLE NOTES (
  N_ID          INTEGER NOT NULL AUTO_INCREMENT(1, 1),
  N_TITLE       VARCHAR(255) NOT NULL,
  N_CONTENT     VARCHAR NOT NULL,
  N_DATE        DATE NOT NULL,
  PRIMARY KEY (N_ID)
);

DROP TABLE PASSWORD IF EXISTS;
CREATE TABLE PASSWORD (
  P_TEXT        VARCHAR NOT NULL,
  PRIMARY KEY (P_TEXT)
);

INSERT INTO PASSWORD (T_TEXT) VALUE ('password');