/*

DROP TABLE NOTES IF EXISTS;
CREATE TABLE NOTES (
  N_ID          INTEGER NOT NULL AUTO_INCREMENT(1, 1),
  N_TITLE       VARCHAR(255) NOT NULL,
  N_CONTENT     VARCHAR NOT NULL,
  N_DATE        DATE NOT NULL,
  PRIMARY KEY (N_ID)
);

DROP TABLE PASSWORDS IF EXISTS;
CREATE TABLE PASSWORDS (
  P_TEXT        VARCHAR NOT NULL,
  PRIMARY KEY (P_TEXT)
);

CREATE TABLE REQUEST (
  R_ID        INTEGER NOT NULL AUTO_INCREMENT(1, 1),
  R_NAME      VARCHAR(255) NOT NULL,
  R_EMAIL     VARCHAR(255),
  R_PHONE     VARCHAR(255),
  R_MESSAGE   LONGTEXT,
  PRIMARY KEY (R_ID)
);*/
